# Generated by Django 6.0.3 on 2026-03-07 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('foundation_year', models.IntegerField()),
                ('club_colours', models.CharField(max_length=100)),
                ('coach_name', models.CharField(max_length=100)),
                ('stadium_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favourite_clubs',
        ),
        migrations.RenameModel(
            old_name='ClubSeasonStats',
            new_name='ClubSeasonStat',
        ),
        migrations.RenameModel(
            old_name='Matches',
            new_name='Match',
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite_club',
            field=models.ManyToManyField(blank=True, to='league.club'),
        ),
        migrations.AlterField(
            model_name='clubseasonstat',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='league.club'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='league.club'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='league.club'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(default='Unknown', max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('market_value', models.BigIntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='league.club')),
            ],
        ),
        migrations.DeleteModel(
            name='Players',
        ),
        migrations.DeleteModel(
            name='Clubs',
        ),
    ]
